In [1]:
import numpy as np

In [30]:
a = np.arange(27).reshape(3, 9)

In [34]:
a

array([[ 0,  1,  0,  3,  0,  5,  0,  7,  8],
       [ 0, 10,  0, 12,  0, 14,  0, 16, 17],
       [ 0, 19,  0, 21,  0, 23,  0, 25, 26]])

In [23]:
b = np.tile(a, 4)

In [24]:
b

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [14]:
c = np.arange(8).reshape((2,2,2))

In [15]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
d = np.repeat(c[:,:,0].reshape(-1), 3)

In [28]:
indices = [list(b), list(d)]

In [29]:
indices

[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 0, 0, 2, 2, 2, 4, 4, 4, 6, 6, 6]]

In [33]:
a[indices] = 0

In [35]:
np.repeat(np.arange(2), 3 * 3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])